[package]
name = "kilogram-store"
description = "Append-only local event storage for Kilogram"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
kilogram-identity = { path = "../kilogram-identity" }
kilogram-protocol = { path = "../kilogram-protocol" }
tempfile.workspace = true
thiserror.workspace = true

[dev-dependencies]
kilogram-ratchet = { path = "../kilogram-ratchet" }

[lints]
workspace = true
